name: khms
description: "PSM2 Project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_core: ^2.27.2
  flutter:
    sdk: flutter
  file_picker: ^8.0.1
  image_picker: ^1.1.0
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  shared_preferences: ^2.2.3
  firebase_storage: ^11.7.4
  intl: ^0.19.0
  provider: ^6.1.2
  firebase_messaging: ^14.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
