name: khms
description: "PSM2 Project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_core: ^2.27.2
  flutter:
    sdk: flutter
  file_picker: ^8.0.1
  image_picker: ^1.1.0
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  shared_preferences: ^2.2.3
  firebase_storage: ^11.7.4
  intl: ^0.19.0
  provider: ^6.1.2
  firebase_messaging: ^14.9.4
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^25.2.7
  flutter_stripe: ^10.2.0
  http: ^1.2.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  flutter_local_notifications: ^17.1.2
  flutter_dotenv: ^5.1.0
  country_picker: ^2.0.26
  photo_view: ^0.15.0
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_icons:
  android: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/foreground_logo.png"
